### ISSUE TITLE
Unable to query data

### ISSUE THREAD

**Issue by jhodges10** [bariolage/gatsby-source-trello-board#2]
I'm getting this error when attempting to build a simple site using the `gatsby-starter-default`.

`Cannot query field "allTrelloCard" on type "Query"`

I have tested my `key`, `token`, and `board_id` all separately in postman using the REST API so I know those are good.

Any help would be appreciated!

**Comment by yuraji** [comment]
This is strange, I was wondering why the plugin was not working and digged into the node_modules.

It turned out in `1.0.7` the `gatsby-node.js` disappeared.

I'm able to use version `1.0.6` of this plugin.

`npm install gatsby-source-trello-board@1.0.6`
`yarn add gatsby-source-trello-board@1.0.6`

**Comment by Takazudo** [comment]
same problem for me too

**Comment by bariolage** [comment]
Sorry for the issue... This is my first package published on npm, it's seem that i had trouble with npmignore and versions cross npm and package.json. I hope your problem will be solved now.
